### ISSUE TITLE
colcon build should NOT fail silently for Python packages

### ISSUE THREAD

**Issue by matthew-grund** [ros2/ros2#1339] opened 2022-10-29 18:56 UTC
## Bug report

**Required Info:**

- Operating System:

Ubuntu 22.04

- Installation type:

binaries

- Version or commit hash:

Humble

- DDS implementation:

whatever is provided with the binary install.

- Client library (if applicable):

rclpy

#### Steps to reproduce issue

```
1. with an ill-formed "package.xml", on a python package, run "colcon build"
2. notice there are no errors or warnings.
3. notice that the python package elements are NOT installed

```
#### Expected behavior

Colcon should report FATAL build errors, at the top-level interface.

#### Actual behavior

Colcon build fails silently.

#### Additional information

Review of the colcon build logs was helpful. But noticing the failure can be difficult, if the package was previously installed.

**Comment by clalancette** [comment] 2022-10-30 14:34
So two things here.

First, I was not able to replicate this behavior with `colcon-core` 0.10.0.  What I did was to remove the last closing `</package>` piece of the XML, but colcon was still able to find and build my python package.  I'm not sure why that is, but it would help if you gave more exact steps on how to reproduce the issue.

Second, this is clearly a problem in colcon, not in ROS 2 proper.  So I'm going to close this out (since you can't transfer issues between organizations), and suggest you open a new bug on https://github.com/colcon/colcon-core instead.

**Closed by clalancette** 2022-10-30 14:34 UTC
