### ISSUE TITLE
Bouncy can't listen/talk to Ardent

### ISSUE THREAD

**Issue by mietzen** [ros2/ros2#579] opened 2018-10-02 06:35 UTC
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - From Source
- Version or commit hash:
  - Latest Bouncy
  - Ardent: release-ardent-20180307
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp, rclpy

#### Steps to reproduce issue
Run demo nodes listener or talker in bouncy and the counterpart in ardent

#### Expected behavior
That I'm able to send/receive message across different versions

#### Actual behavior
Neither node or topic is found

**Comment by clalancette** [comment] 2018-10-02 12:30
Unfortunately, this is expected behavior.  During Ardent we used DDS Partitions to separate nodes/namespaces, but after discussing with the DDS vendors, we found that that was not a good idea.  So in Bouncy we changed to having a custom prefix on the topic and service names.  Thus, the two implementations cannot really talk to each other.

I'm going to close this out, since it isn't something we can fix, but feel free to comment more if you have more questions about this behavior.

**Closed by clalancette** 2018-10-02 12:30 UTC
