### ISSUE TITLE
Build from Source Fails

### ISSUE THREAD

**Issue by gnorthfork** [ros2/ros2#413] opened 2017-10-13 23:07 UTC
Not sure if this is the correct place to post this.  If not, my apologies.

OS: Windows 10
Framework:  VS2017,  with latest updated applied.
Install procedure:  https://github.com/ros2/ros2/wiki/Windows-Development-Setup

Followed the steps as instructed, no issues, until time to build ROS2 source.   Unresolved external symbols  when trying to link /build/builtin_interfaces/Release/builtin_interfaces_s__rosidl_typesupport_c.lib.

Anyone else having this issue?  All comments appreciated.

[build.log](https://github.com/ros2/ros2/files/1384200/build.log)

## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - From Source
- Version or commit hash:
  - 
- DDS implementation:
  - Fast-RTPS 
- Client library (if applicable):
  - NA

**Comment by dirk-thomas** [comment] 2017-10-13 23:10
ROS 2 currently only supports Visual Studio 2015. Can you reproduce the same problem with that version?

**Comment by gnorthfork** [comment] 2017-10-14 04:42
Thanks for the suggestion.  Just downloaded VS2015 Professional.  

1. Removed the /dev/ros2 and reloaded from GIT.  
2. Open command prompt as administrator, and executed the VS2015 shell command.
3. From dos shell, verified all environment variables referenced vs2015 and not vs2017
4. Ran python src\ament\ament_tools\scripts\ament.py build

Unfortunately, same error at same place in the build process.

Any other ideas?

**Comment by clalancette** [comment] 2017-10-18 17:52
Would you mind attaching another log with your latest output?  We just want to check a few things with the VS2015 setup.  Thanks.

**Comment by gnorthfork** [comment] 2017-10-19 04:30
Sorry, I gave up and uninstalled ROS2

On Wed, Oct 18, 2017 at 10:53 AM, Chris Lalancette <notifications@github.com

**Comment by clalancette** [comment] 2017-10-19 13:16
All right, thanks for the response.  Since we don't have a reproducer for now, I'm going to close this out.  If you get a chance to try this out again in the future, feel free to re-open this bug and we'll try to track it down.

**Closed by clalancette** 2017-10-19 13:16 UTC
Labels: more-information-needed
