### ISSUE TITLE
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.

### ISSUE THREAD

**Issue by AllenChienXXX** [ros2/ros2#1492] opened 2023-10-09 17:45 UTC
i'm trying to build my ros2 package with colcon,

python version == 3.8.18
setuptools version == 58.2.0 (I downgrded it but it doesn't work for me)
OS: Ubuntu linux LTS arm64
error:
Starting >>> my_robot_controller
--- stderr: my_robot_controller                   
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< my_robot_controller [0.49s]

Summary: 1 package finished [0.76s]
  1 package had stderr output: my_robot_controller

is there other way to fix this issue without deleting the setuptools requirement?

**Comment by clalancette** [comment] 2023-10-09 17:49
> is there other way to fix this issue without deleting the setuptools requirement?

In short: no.  The longer answer is that we need an entirely new approach to distributing Python tools, which we've been working on: https://discourse.ros.org/t/call-for-testing-standards-based-python-packaging-with-colcon/32008

This is a duplicate of https://github.com/ament/ament_cmake/issues/382 , so closing it in favor of that.

**Closed by clalancette** 2023-10-09 17:49 UTC

**Comment by ros-discourse** [comment] 2024-11-20 17:01
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/status-of-colcon-building-standards-based-python-packages/40578/11
