### ISSUE TITLE
Action server does not receive goals after the first one has terminated

### ISSUE THREAD

**Issue by Agent-JH** [ros2/ros2#1609] opened 2024-10-03 12:06 UTC
## Bug report

**Required Info:**

- Operating System: 
Ubuntu 22.04.5 LTS
- Installation type:
Ubuntu deb packages
- DDS implementation:
Default one (I guess eProsima Fast-DDS)
- Client library:
rclpy

### Explanation
I have already written an explanation [here](https://robotics.stackexchange.com/questions/113168/action-server-does-not-receive-goals-after-the-first-one-has-terminated) on robotics stackexchange, I will copy that here for our convenience.

I'm on ROS2 Humble using python. I am building an node to process the feedback of the action server of a different node. Let's call the first node Tracker and the second one Detector.

Tracker implements an action server providing all the possible callbacks, in a `MultiThreadedExecutor` with `ReentrantCallbackGroup` as callback group for those callbacks. A similar arrangement is also present in Detector. Tracker also has an action client in order to send to Detector the specific goal we want to track the feedback of. Detector instead has a subscriber that updates a message object from which it detects what it needs to detect.

The problem is that after the first goal to Tracker has terminated (I send the goal via terminal using `ros2 action send_goal /tracker_action_name <tracker goal object>` and cancel it with `ctrl+c`) if I try to send a new goal, either in the same or in a different terminal, **the new goal is not received by Tracker**.

The terminal remain stuck in ``Waiting for an action server to become available...`` and nothing changes. **The Tracker's callback for the goal request is not triggered** and it is necessary to restart Tracker to process a new goal.

Using `ros2 action list` the action is still listed and with `ros2 action info /tracker_action_name` I can see that Tracker still provides the server. Yet, it remain unresponsive to new goals.

This behavior is not present in Detector. Detector has no problem receiving subsequent goals or multiple goals at the same time, despite sharing almost the same structure of Tracker. It has a problem with `rclpy.wait_for_message.wait_for_message` which occasionally does not wait for the time provided, but I don't think it's relevant for this case.

#### Steps to reproduce issue
[Here](https://github.com/user-attachments/files/17243783/bug.14.examples.zip) is a zip containing a couple of packages to reproduce the bug.
- Open 4 terminals
- Launch the following commands:
    - `ros2 launch simple_package detector.launch.py`
    - `ros2 launch simple_package tracker.launch.py`
    - `ros2 topic pub /detection_topic std_msgs/msg/String "data: 'test_string'" -r 30`
    - `ros2 action send_goal --feedback /tracking_action simple_interfaces/action/Integer "request_number: 3"`

#### Expected behavior
After the goal to tracker has been cancelled (either by `ctrl-c` or by code) and the action terminated, sending a new goal should trigger the relevant callbacks from Tracker's `action_server`.

#### Actual behavior
Tracker's `action_server` remain unresponsive to new goals request, which **do not** trigger any callback and are not processed. 

#### Additional information
Nowhere it is stated that `action_client` and an `action_server` are not compatible to be implemented in the same node, since subscriber and publishers apparently have no problems (Detector contains a subscriber after all).

I am attempting to separate `action_client` and `action_server` by having two different nodes implementing them in the same executable, but I am encountering problems as it appears that it is not possible to have them communicate by calling methods while preserving both logging and multi-threading. It might warrant a secondary bug report.

**Comment by fujitatomoya** [comment] 2024-10-03 23:53
The reason is `rclpy.spin_until_future_complete` in the `Tracker.execute_callback`.

1st call on `rclpy.spin_until_future_complete`, it will add node to the global executor, and remove the node from the global executor. after this process, the node does not belong to any executor. that is okay in this `Tracker.execute_callback` scope, because other `rclpy.spinXXX` uses the global executor in this thread. but eventually node ends up having empty executor in this callback. that means, next `wait_for_ready_callbacks` call of `MultiThreadedExecutor` does not take any data from this `Tracker` node, because it does not belong to this `MultiThreadedExecutor` any more. this is the root cause of hung-up. (following is gdb python stack trace of this hung-up issue.)

```bash
(gdb) py-bt
Traceback (most recent call first):
  <built-in method wait of PyCapsule object at remote 0x7f64e7357450>
  File "/root/ros2_ws/humble_ws/install/rclpy/local/lib/python3.10/dist-packages/rclpy/executors.py", line 608, in _wait_for_ready_callbacks
    wait_set.wait(timeout_nsec)
  <built-in method next of module object at remote 0x7f64e7ad8950>
  File "/root/ros2_ws/humble_ws/install/rclpy/local/lib/python3.10/dist-packages/rclpy/executors.py", line 711, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/root/ros2_ws/humble_ws/install/rclpy/local/lib/python3.10/dist-packages/rclpy/executors.py", line 775, in _spin_once_impl
    handler, entity, node = self.wait_for_ready_callbacks(
  File "/root/ros2_ws/humble_ws/install/rclpy/local/lib/python3.10/dist-packages/rclpy/executors.py", line 794, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/root/ros2_ws/humble_ws/install/rclpy/local/lib/python3.10/dist-packages/rclpy/executors.py", line 294, in spin
    self.spin_once()
  File "/root/ros2_ws/humble_ws/build/simple_package/simple_package/tracker.py", line 142, in main
    executor.spin()
  File "/root/ros2_ws/humble_ws/install/simple_package/lib/simple_package/track", line 33, in <module>
    sys.exit(load_entry_point('simple-package', 'console_scripts', 'track')())
```

calling the synchronous operation in the callback is not recommended design for the application. see more details for https://docs.ros.org/en/foxy/How-To-Guides/Sync-Vs-Async.html#sync-deadlock. after all, i would recommend to use `async & await` manner in the callback instead of calling the `spin` functions in the callback. you can refer to the example https://github.com/ros2/examples/blob/rolling/rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client_asyncio.py

besides, i really do not think it needs to call `spin_once` to wait some duration... i would use `rate.sleep()` instead.

related issue: https://github.com/ros2/rclpy/issues/1337, and `spin_until_future_complete` now can be called in the callback, if executor argument is appropriately set. see more details for https://github.com/ros2/rclpy/pull/1316

**Comment by Agent-JH** [comment] 2024-10-04 16:49
> after all, i would recommend to use async & await manner in the callback instead of calling the spin functions in the callback

Having replaced all `rclpy.spin_until_future_complete` with `await` calls directly with the async functions, and turning `execute_callback` into an async, seems to work fine. I post here the modified `tracker.py` just to make sure, I am not too much familiar with asynchronous tasks in python.

```python
import rclpy, rclpy.action, rclpy.node, rclpy.executors
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.action import ActionServer, GoalResponse, CancelResponse

import simple_interfaces.action
import simple_interfaces.action._integer

class Tracker(rclpy.node.Node):

  def __init__(self):
    super().__init__('tracker')
    self.log_info('Setting up node...')

    self.feedbacks_received = 0

    self.action_server = ActionServer(
      self,
      simple_interfaces.action.Integer,
      'tracking_action',
      goal_callback=self.goal_callback,
      handle_accepted_callback=self.handle_accepted_callback,
      cancel_callback=self.cancel_callback,
      execute_callback=self.execute_callback,
      callback_group=ReentrantCallbackGroup()
    )

    self.detector_client = None
    
    self.log_info('Setup complete')

  def goal_callback(self, goal_request:simple_interfaces.action.Integer.Goal):
    self.log_info('Received goal request')
    return GoalResponse.ACCEPT
    
  def handle_accepted_callback(self, goal_handle:rclpy.action.server.ServerGoalHandle):
    self.log_debug('Starting new goal')
    goal_handle.execute()
  
  def cancel_callback(self, goal_handle:rclpy.action.server.ServerGoalHandle):
    self.log_debug('Cancel request')
    return CancelResponse.ACCEPT


  async def execute_callback(self, goal_handle:rclpy.action.server.ServerGoalHandle):
    self.log_info('Starting action')
    self.feedbacks_received = 0

    action_client = rclpy.action.ActionClient(
      self,
      simple_interfaces.action.Integer,
      'detection_action',
      callback_group=ReentrantCallbackGroup()
    )

    self.log_debug('Waiting for detector action server...')

    action_client.wait_for_server()

    self.log_debug('Detector action server online')

    goal_msg = simple_interfaces.action.Integer.Goal()
    goal_msg.request_number = goal_handle.request.request_number

    self.log_debug('Sending goal request...')

    ##############################
    detector_client_goal_handle = await action_client.send_goal_async(
      goal_msg,
      feedback_callback=self.process_feedback
    )

    if detector_client_goal_handle is None:
      self.log_error('Detector action server did not respond to the request')
      return False

    if not detector_client_goal_handle.accepted:
      self.log_error('Detector action server rejected the request')
      return False

    self.log_debug('Detector action server accepted the request')

    while rclpy.ok() and not goal_handle.is_cancel_requested:
      self.get_logger().debug("Let's wait...", once=True)
      self.log_debug(f'Feedback received: {self.feedbacks_received}')
    
    ##############################
    cancel_future_result = await detector_client_goal_handle.cancel_goal_async()
    
    if cancel_future_result is not None and len(cancel_future_result.goals_canceling) > 0:
      self.log_debug('Yolo server correctly cancelled the goal')
    else:
      self.log_error('Error upon cancel request to the Yolo server')

    result = simple_interfaces.action.Integer.Result()
    result.result_number = self.feedbacks_received
    self.log_debug(f'Final result [{result.result_number}]')
    goal_handle.succeed()
    self.log_info('Action terminated')
    return result
  
  def process_feedback(self, feedback_msg:simple_interfaces.action._integer.Integer_FeedbackMessage):
    self.log_debug(f"Feedback received: {feedback_msg.feedback.feedback_number}")
    self.feedbacks_received += 1
    pass


  def log_info(self, log: str) -> None:
    self.get_logger().info(log)

  def log_debug(self, log: str) -> None:
    self.get_logger().debug(log)

  def log_error(self, log: str) -> None:
    self.get_logger().error(log)

  def log_warn(self, log: str) -> None:
    self.get_logger().warn(log)


def main(args=None):
  rclpy.init(args=args)
  executor = rclpy.executors.MultiThreadedExecutor()
  action_server = Tracker()
  executor.add_node(action_server)
  try:
    executor.spin()
  except KeyboardInterrupt:
    pass

if __name__ == '__main__':
  main()
```
I have yet to test it with my original code, but it works fine on this example.

**Comment by fujitatomoya** [comment] 2024-10-04 17:38
@Agent-JH thanks for the quick reply. happy to hear that it is working for your application. if you are okay, please close this issue or you can keep this reopen if anything needs to be added or enhanced in client libraries.

**Closed** 2024-10-06 12:33 UTC
