### ISSUE TITLE
Occasional "connection establishment" issue between ROS 2 nodes across platforms 

### ISSUE THREAD

**Issue by Seiwert** [ros2/ros2#651] opened 2019-01-28 21:25 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - ROS 2 Bouncy (built from source)
- Version or commit hash:
  - Bouncy
- DDS implementation:
  -  Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
Apologies ahead of time as this one is kind of a mess. To summarize, I'm having issues getting multiple agents to communicate when initially starting ROS 2 nodes with rclpy. Also, this issue only happens ~10-30% of the time so it's hard to replicate.

The gist is I have a node running on a laptop and nodes running on several other robotic platforms. The laptop node is outputting a "heartbeat" message (uint8 message essentially). The shortened code that runs on the laptop is as follows:

```python
import os
import sys
import rclpy
from rclpy.node import Node
from c2_msgs.msg import HeartBeat

class ControlNode(Node):
    def __init__(self, droneList):
        rclpy.init()
        Node.__init__(self, 'control')
        self.heartbeatPub = self.create_publisher(HeartBeat, 'heartbeat')
        self.heartbeatTimer = self.create_timer(1.0, self.heartbeatCallback)
        self.generateSubscribers(droneList) # subscribes to robots dynamically
        self.heartbeat_monitor = {}

    def heartbeatCallback(self):
        """
        HeartBeat message info.
        1 = Online
        2 = Pause
        3 = Kill
        4 = DEAD
        """
        self.heartbeatPub.publish(self.heartbeatMessage)

    def heatbeatResponse_callback(self, drone, msg): #works because subscription is done with python partial function
        self.heartbeat_monitor[drone] = [msg.data, datetime.datetime.now()]

````
So as you can see, the laptop is publishing this "heartbeat" message once a second, so nothing too crazy going on with this.

Now, for the vehicles, the code in error is as follows:

```python
import sys
import os

import rclpy
from rclpy.node import Node
from c2_msgs.msg import HeartBeat
import threading


class ReceiveAndStatus(Node):
    def __init__(self):
        rclpy.init()
        self.whoami = self.robotConfig['robot info']['whoami']
        super().__init__('commandReceive', namespace=self.whoami)
        self.create_subscription(HeartBeat, '/heartbeat', self.heartbeatReceive_callback)
        self.heartbeatPub = self.create_publisher(HeartBeat, 'heartbeat')
        self.comm_established = False
        self.haveConnection = False
        self.connectionTimer = 5
        self.is_shutdown = False
        self.spin_lock = False

    def heartbeatReceive_callback(self, msg):
        heartbeat_msg = HeartBeat()
        heartbeat_msg.data = HeartBeat.ALIVE
        self.heartbeatPub.publish(heartbeat_msg)
        if msg.data == HeartBeat.ALIVE:
            self.comm_established = True #class property that confirms we made contact with the C2 node at least once. 
            self.haveConnection = True
            self.connectionTimer = 5

    def spin(self):
        while not self.is_shutdown: #TODO: Update for rclpy is not shutdown function
            self.spin_lock = True
            rclpy.spin_once(self, timeout_sec=0.3)
            if self.connectionTimer > 0:
                self.publishLogs()
                self.connectionTimer -= 1
                if self.btPublished == False:
                    self.btPub.publish(self.btmsg)
                    self.btPublished = True
            else:
                self.haveConnection = False
            self.spin_lock = False

    def shutdown(self):
        self.is_shutdown = True
        while True: # Have to do this because system freezes if shutdown is initiated while inside of spin_once function
            if not self.spin_lock:
                self.tacticHandler.stop()
                self.destroy_node()
                rclpy.shutdown()
                return

def main():
    global receiveAndStatusNode
    global hybridThread
    retry_count = 5
    try:
        hybridThread = threading.Thread(target=receiveAndStatusNode.spin)
        hybridThread.daemon = True
        print("Starting Hybrid Node.")
        hybridThread.start()
        time.sleep(5)
        if not receiveAndStatusNode.comm_established:
            while retry_count > 0 and not receiveAndStatusNode.comm_established:
                print('Communication failed. Retrying')
                retry_count -= 1
                receiveAndStatusNode.shutdown()
                hybridThread.join()
                receiveAndStatusNode = ReceiveAndStatus()
                hybridThread = threading.Thread(target=receiveAndStatusNode.spin)
                hybridThread.daemon = True
                hybridThread.start()
                time.sleep(5)
            if retry_count > 0:
                print("Communication established after {0} attempts".format((5-retry_count)))
            else:
                print("Failed to establish after 5 attempts. Exiting.")
                receiveAndStatusNode.shutdown()
                hybridThread.join()
                sys.exit(0)
                return
        while hybridThread.isAlive():
            time.sleep(5)
    finally:
        receiveAndStatusNode.shutdown()

if __name__ == '__main__':
    global receiveAndStatusNode
    receiveAndStatusNode = ReceiveAndStatus()
    main()

```

So, lots of bad conventions here but all of this came out of necessity and time constraints.

#### Expected/Actual behavior
Ideally, on the ROS 2 node on the robots, I would expect the node to run and automatically start subscribing and publishing on the heartbeat topic without the need for all of the threading. However, what I see is that the two nodes don't always "form a connection" for lack of better terms. Essentially what will happen is the laptop will produce the topic and I can echo it on the laptop, but the robot never sees the heartbeat messages. Worst part is if the robot doesn't initially see the messages then it typically never sees the messages. The only way I've gotten it to see the heartbeat messages when it doesn't see them is to restart the entire node. That is what you can see from logic in the main function. We expect the ROS 2 node to receive a heartbeat message within 5 seconds of booting and if it doesn't, that thread is killed and a new one is created. Whenever this happens, I typically see that the process has to be killed 3 times before that first connection is made. 

Also worth noting that I see all the messages in Wireshark even though that connection hasn't formed yet. I've attached a screenshot showing the output from the ROS 2 node on the robot with Wireshark showing that the messages are being sent even though the ROS 2 node isn't registering them.

![ros 2 binding issue](https://user-images.githubusercontent.com/4229602/51866757-05c43a00-2307-11e9-9c16-79c3f3ced070.png)

#### Additional information

This issue is not hardware dependent. I've encountered this issue on Odroid-XU4s, Nvidia TX2s, and Intel Aero compute boards. All running Ubuntu 16.04 with ROS 1/2 inside of a Docker container. I haven't fully transitioned to Crystal yet but will note whether or not I continue seeing this issue with new release.

**Comment by dirk-thomas** [comment] 2019-01-28 21:32
> I haven't fully transitioned to Crystal yet but will note whether or not I continue seeing this issue with new release.

Please do so and comment with the results. Before it doesn't make much sense to investigate for us.

**Comment by dirk-thomas** [comment] 2019-01-29 06:48
I would suggest to try a different rmw implementations first. That way we will have a strong indicator if the problem is the same across them or specific to one of them.

**Comment by 43970117** [comment] 2019-01-29 11:18
I also met this kind of problem. Some nodes are running in vehicles with Ubuntu 16.04,  a center node is running in PC with Windows.
Window ROS version is Bouncy Bolson, installed with pre-built binary;  Ubuntu ROS version is Master branch at Bouncy Bolson time, is built with source code.
They have 30% probability failure in setting connection. An observation: ros2 topic echo command in either platform can help connection setting, it helps topic matching.
DDS used is fastrtps

The below is a case that ros2 topic echo <topic>, trigger a successful topic receiving:
Jan 28 06:39:59 localhost onParticipantDiscovery[7151]: onParticipantDiscovery is called, node is rcds185, status is 0  
Jan 28 06:39:59 localhost onParticipantDiscovery[5197]: onParticipantDiscovery is called, node is _ros2cli_node_7151, status is 0  
Jan 28 06:39:59 localhost onParticipantDiscovery[7151]: onParticipantDiscovery is called, node is vehicle_access_3, status is 0  
Jan 28 06:39:59 localhost onParticipantDiscovery[7151]: onParticipantDiscovery is called, node is rcds183, status is 0  
Jan 28 06:39:59 localhost onParticipantDiscovery[7151]: onParticipantDiscovery is called, node is rcds186, status is 0  
Jan 28 06:39:59 localhost onParticipantDiscovery[7151]: onParticipantDiscovery is called, node is rcds182, status is 0  
Jan 28 06:39:59 localhost onParticipantDiscovery[7151]: onParticipantDiscovery is called, node is rcds184, status is 0  
Jan 28 06:39:59 localhost onPublicationMatched[7151]: onPublicationMatched, Topic name: rt/parameter_events
Jan 28 06:39:59 localhost last message repeated 5 times
Jan 28 06:39:59 localhost onSubscriptionMatched[5197]: onSubscriptionMatched, status is 0
Jan 28 06:39:59 localhost onSubscriptionMatched[5197]: onSubscriptionMatched, GUIDPrefix: 1.15.1.125.239.27.0.0.0.0.0.0.
Jan 28 06:39:59 localhost onSubscriptionMatched[5197]: onSubscriptionMatched, GUIDEntity ID: 0.0.1.3
Jan 28 06:39:59 localhost onSubscriptionMatched[5197]: onSubscriptionMatched, Topic name: rt/parameter_events
Jan 28 06:39:59 localhost onNewDataMessage[5197]: onNewDataMessage, unreadCount 1
Jan 28 06:39:59 localhost onNewDataMessage[5197]: onNewDataMessage, Topic name: rt/parameter_events
Jan 28 06:39:59 localhost onNewDataMessage[5197]: onNewDataMessage, unreadCount 1
Jan 28 06:39:59 localhost onNewDataMessage[5197]: onNewDataMessage, Topic name: rt/clock
Jan 28 06:39:30 localhost onSubscriptionMatched[7151]: onSubscriptionMatched, status is 0
Jan 28 06:39:30 localhost onSubscriptionMatched[7151]: onSubscriptionMatched, GUIDPrefix: 1.15.1.125.77.20.0.0.0.0.0.0.
Jan 28 06:39:30 localhost onSubscriptionMatched[7151]: onSubscriptionMatched, GUIDEntity ID: 0.0.27.3
Jan 28 06:39:30 localhost onSubscriptionMatched[7151]: onSubscriptionMatched, Topic name: rt/agv185_to_tcs
Jan 28 06:39:30 localhost onPublicationMatched[5197]: onPublicationMatched, Topic name: rt/agv185_to_tcs

**Comment by kervel** [comment] 2019-05-22 10:05
Hello,

We had the same problem, but in our case its on one single (18.04) machine. we have a hard time creating a testcase (even running the same nodes + a rosbag with camera frames already makes the issue impossible to reproduce).
We had the issue on bouncy (then we worked around by switching to another rmw), again in crystal, and we just tried yesterdays master branch and still had the issue.

Some things we noted:
* we also see wrong subscriber / publisher count in the "ros2 topic info" output when the problem happens.
* we have nodes that don't exit cleanly and they remain in the node list after they are gone. we clear it by doing "ros2 daemon stop". From the documentation the daemon shoudln't matter. we also have non-unique node names (we use the showimage node from image_tools multiple times)
* when we try (in rviz2) to show an image, it sometimes shows "no image" until we restart rviz, so rviz fails to subscribe but it still shows the topics in the topic list.
* sometimes we can "solve" the problem by just doing ros2 topic echo on the problematic topic and everything starts magically working. but most of the time this doesn't help.

i think we'll have to switch to another rmw again, but any hints on how to debug this further would be greatly appreciated, we'd really like to stick to the default rmw. i already tried to reproduce using a huge number of cam2image and showimage nodes alone, but it seems only to happen in very specific conditions.

Frank

**Comment by kervel** [comment] 2019-05-22 13:13
small update: we couldn't reproduce the problem with opensplice or connext RTI, but the performance of the image topics of both connext and opensplice is horribly slow (less than 1fps) compared to fastrtps, so for us that's not a solution.

**Comment by MiguelCompany** [comment] 2019-05-28 12:22
This may have been solved by eProsima/Fast-RTPS#541 and eProsima/Fast-RTPS#539, which are already merged on master.

@kervel and @43970117 would you mind checking against master?

**Comment by kervel** [comment] 2019-05-29 08:00
(cc @phinx110 ) we have been doing tests with latest master branch now. so far it looks like our issue has been fixed (at least we haven't be able to reproduce yet). Will do more tests.

**Comment by kervel** [comment] 2019-06-05 09:38
Hello,

the problem has not appeared anymore since we upgraded 8 days ago. So for us this is no longer an issue.

Frank

**Comment by clalancette** [comment] 2019-09-24 19:53
It looks like this has generally been fixed.  I'm going to close this out, but feel free to reopen if this is still affecting you.

**Closed by clalancette** 2019-09-24 19:53 UTC
Labels: more-information-needed
