### ISSUE TITLE
Client requests are not sent immediately

### ISSUE THREAD

**Issue by esteve** [ros2/ros2#111] opened 2015-09-03 00:08 UTC
Services tests sleep for a short while to ensure that the client actually sends the request:

https://github.com/ros2/system_tests/pull/42#discussion-diff-38600456R62

**Comment by jacquelinekay** [comment] 2015-11-11 00:53
@esteve Do you mind if a mark this as a duplicate of duplicate of ros2/rmw_connext#112?

**Comment by esteve** [comment] 2015-11-11 00:56
@jacquelinekay sure, no problem!

**Comment by wjwwood** [comment] 2016-01-26 00:07
I'm just trying to clean up some old tickets. @esteve can we close this if it is a duplicate of ros2/rmw_connext#112? Or perhaps vice versa?

**Comment by esteve** [comment] 2016-01-26 00:11
I think it's safe to close this ticket and focus on @jacquelinekay 's ros2/rmw_connext#112

**Comment by wjwwood** [comment] 2016-01-26 00:12
Ok, thanks.

**Comment by dirk-thomas** [comment] 2016-01-26 00:13
I think `sending immediately` and `deterministic` are very different. Imo sending the request immediately would be good to support (if possible). Either this should be explicitly mentioned in the other ticket or this should stay open.

**Comment by wjwwood** [comment] 2016-01-26 00:14
Well I'll reopen it then. If someone consolidates the issues in the other ticket then they can re-close this one.

**Comment by dirk-thomas** [comment] 2019-09-05 19:48
By now there is an API for the client to check / wait for the service to be available which is the right thing to do in an asynchronous system. Closing.

**Closed by dirk-thomas** 2019-09-05 19:48 UTC
Labels: duplicate
