### ISSUE TITLE
ros2 subscriber (foxy version) not able to subscribe the topics (dashing version)

### ISSUE THREAD

**Issue by pulkitgoyal1506** [ros2/ros2#990] opened 2020-07-29 19:16 UTC
## Description
In my setup, I have two PCs on a LAN. PC-1 has the ROS (dashing version) running on it with topics publishing some data. PC-2 has the ROS (foxy version) running on it subscribing to PC-1 topics. 
On PC-2, I am subscribing the data being published by ros topics on PC-1.

### Expected Behavior
I expect the ros foxy on PC-2 to be able to subscribe to the data being published from ros dashing on PC-1.

### Actual Behavior
Foxy is not able to subscribe any data coming from dashing topics. Executing 'ros2 topic list' on foxy is listing all the topics running on dashing. But 'ros2 topic echo' is not subscribing to any of those topics.

## To Reproduce

- PC1: ROS2 (dashing) publishing data on some topics
- PC2: ROS2 (foxy) recording data coming from PC-1

Example:
On PC-1 execute following on terminal:
```
ros2 topic pub /chatter std_msgs/String "data: Hello world"
```
On PC-2 execute following on terminal:
``` 
ros2 topic echo /chatter
(won't be able to subscribe to anything)
```

## System
- PC1: ROS 2 Dashing, Ubuntu 18.04
- PC2: ROS 2 Foxy, Ubuntu 20.04

**Comment by Karsten1987** [comment] 2020-07-29 19:21
As mentioned in https://github.com/ros2/rosbag2/issues/474, this is not a rosbag related problem. You can verify this by running a `ros2 topic pub /hello_from_dashing std_msgs/msg/String "{data: Hello World}"` on Dashing side and try to subscribe with `ros2 topic echo /hello_from_dashing` on Foxy side.

I've changed your title appropriately. Feel free to correct me if you see this as inaccurate.

**Comment by clalancette** [comment] 2020-08-02 01:54
We don't support communications between major releases of ROS.  In many cases it happens to work, but if it doesn't (which it clearly doesn't in this case), we don't guarantee to spend time on it.  For that reason, I'm going to close this.  If you happen to find the reason, and want to open a pull request to fix it, we'll happily review it.

**Closed by clalancette** 2020-08-02 01:54 UTC

**Comment by Sollimann** [comment] 2021-11-26 14:18
@pulkitgoyal1506 @Karsten1987 @clalancette any updates on this? Did you get it to work, if so, how? we also have the same issue. The robot itself is running ros2 dashing, while our software stack is running ros2 foxy.

**Comment by adamdbrw** [comment] 2021-11-26 14:20
@Sollimann we did make it work previously. I don't remember the exact setup, but surprisingly, setting one to FastDDS and the other to CycloneDDS solved the problem.

**Comment by Sollimann** [comment] 2021-11-26 14:31
@adamdbrw Okey, I see. which is using which DDS? Did you use this guide to set it up? https://docs.ros.org/en/foxy/Installation/DDS-Implementations.html

And also, might be a bit difficult to configure the ros2 dashing hosted on their RPI (which we have no insight to) in a docker container to use a different DDS :thinking:

**Comment by adamdbrw** [comment] 2021-11-26 14:36
It was probably FastRTPS on Dashing side (so no need to configure) and CycloneDDS on Foxy side. But as I said, it was a while ago so you need to check it yourself. Hope this helps.

**Comment by Sollimann** [comment] 2021-11-26 14:38
Great, thanks for the help! :) Will let you know if it worked or not!

**Comment by adamdbrw** [comment] 2021-11-26 14:41
Thanks, I would be interested to know. As @clalancette said, cross-version between major releases is not supported (as opposed to cross-vendor for same ROS version), so it is possible that updated rmw packages (there were several patches for each since I ran my setup) no longer allow this kind of communication.

**Comment by Sollimann** [comment] 2021-12-01 16:13
@adamdbrw I tried the following the guide [Working-with-Eclipse-CycloneDDS](https://docs.ros.org/en/foxy/Installation/DDS-Implementations/Working-with-Eclipse-CycloneDDS.html) to configure ros2 foxy to use Cyclone DDS and update my docker image as such:

DDS specifications on line **20, 31, 32**

![image](https://user-images.githubusercontent.com/25263842/144267380-c0e08ede-6d39-4b17-b76f-c5bb3313acef.png)

Then I built the docker image for `linux/arm64` (arm64 required on rpi and jetson) using the following command:

```sh
$ docker build --platform linux/arm64 -t my-ros2-foxy-arm64-image .
```
and then ran it on my Nvidia Jetson using:

```sh
$ docker run ros2-foxy my-ros2-foxy-arm64-image --network host --privileged true
```

However, I'm still not able to publish/subscribe between foxy and dashing. **Suggestions for things I can try to make it work?** :) . The robot raspberry PI (top left) running ros2 dashing and the Nvidia Jetson (top right) running ros2 foxy is connected to the same network via a network switch (blue box with ethernet cables in bottom):

![image](https://user-images.githubusercontent.com/25263842/144269580-3339198f-bcbb-4179-b686-e40e0a5a2713.png)

**Comment by adamdbrw** [comment] 2021-12-01 16:19
My setup was on a different architecture. Did you test Dashing to Dashing?
There are bridging solutions you can try if this doesn't work for you, but it is best to narrow it down and understand the reason.
It is also possible that earlier versions of rmw packages worked in this setup and current versions no longer do. 
I am certain it did run for us (I confirmed it was Dashing to Foxy) and we used this setup successfully for quite a while (but again, different platform, different versions of rmw packages).
