### ISSUE TITLE
Parameter with default value of empty array is incorrectly inferred as a BYTE_ARRAY

### ISSUE THREAD

**Issue by jackiescanlon** [ros2/ros2#1518] opened 2024-02-05 14:33 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - Apt
- Version or commit hash:
  - ros-iron-rclpy apt package version 4.1.4-1jammy.20231205.160931
- DDS implementation:
  - CycloneDDS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

1. Create a new node with this code
```py
#!/usr/bin/env python3
import rclpy
import rclpy.node


class ListParamDemo(rclpy.node.Node):
    def __init__(self):
        super().__init__("list_param_demo")

        self.declare_parameter("param_1", [])


def main():
    rclpy.init()
    node = ListParamDemo()
    rclpy.spin(node)


if __name__ == "__main__":
    main()
```
2. Run it, including passing in a value for `param_1` that is an array of strings
```
ros2 run my_package list_parameter_node.py --ros-args -p param_1:='["hello", "world"]'
```

#### Expected behavior
Node runs and accepts the param values

#### Actual behavior
Node fails to run, because it claims that `param_1` is of type `BYTE_ARRAY`
```
rclpy.exceptions.InvalidParameterTypeException: Trying to set parameter 'param_1' to '['hello', 'world']' of type 'STRING_ARRAY', expecting type 'BYTE_ARRAY'
```

#### Additional information
Specifying a type when declaring the descriptor does nothing, as expected since `rclpy` [explicitly states](https://github.com/ros2/rclpy/blob/986721b9a5a6ce16866d0c617f6b99b3f8ce80c2/rclpy/rclpy/node.py#L368-L369) that the type will be ignored in this scenario.

As a workaround, I avoid putting an empty list as the default value for a parameter. However for optional parameters, this means that the value for `param_1` will never be set, and therefore `ros2 param dump` won't ever work, due to #1517.

**Comment by clalancette** [comment] 2024-02-06 17:13
This is a duplicate of https://github.com/ros2/rclpy/issues/912 , so closing it.

**Closed by clalancette** 2024-02-06 17:13 UTC
