### ISSUE TITLE
problems about code style in ros2

### ISSUE THREAD

**Issue by lxbeyond** [ros2/ros2#452] opened 2018-01-26 09:36 UTC
I have test rclpy program in examples reps, and I'm confused about the comments "We do not recommend this style as ROS 2 provides timers for this purpose, and it is recommended that all nodes call a variation of spin." int file examples/rclpy/topics/minimal_publisher/publisher_local_function.py . Is it just a code style problem or that this will make difference to the performance of program ? I used to work in ros1, and familiar to the code style in file "publisher_local_function.py", need I change the code style ?

**Comment by sloretz** [comment] 2018-01-26 16:02
I see this is a duplicate of the issue ros2/examples#201. I'll close this one since the question involves code from the examples repo.

**Closed by sloretz** 2018-01-26 16:02 UTC
