### ISSUE TITLE
Ardent patch release 1

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#454] opened 2018-01-30 22:43 UTC
For an Ardent patch release 1 we will cherry-pick the minimal changes which are necessary to address important issues. The high level goals are:
  * provide `rviz` for Windows
  * fix problem(s) in FastRTPS, e.g. https://github.com/eProsima/Fast-RTPS/issues/181
  * fix problem with include path order in `rosidl`
  * Provide `ros_environment` for the env vars specified in REP 149

We will do the following:

- [x] Create PRs using a to be created source branch named `ardent-patch1` targeting the existing `ardent branch`:
  - [x] `rviz` @wjwwood (https://github.com/ros2/rviz/pull/188)
  - [x] `pluginlib` @wjwwood (https://github.com/ros/pluginlib/pull/98)
  - [x] `resource_retriever` @wjwwood (https://github.com/ros/resource_retriever/pull/18)
  - [x] `fastrtps` @dirk-thomas (ros2/ros2#455)
  - [x] `rosidl` @mikaelarguedas (https://github.com/ros2/rosidl/pull/262)
  - `ros_environment` @dirk-thomas (this doesn't need a PR, the `ardent` branch is already the state we want to release)
- [x] Check if any packages should be updated on the macOS / Windows nodes (and if it affects the instructions): @wjwwood
- [x] Roll some fat archives to check they "address" the problems.
- [x] Merge the PRs.
- [x] Make a patch release in the affected repos.
- [x] Do the `bloom` releases.
  * @nuclearsandwich mentioned addressing a minor issue in the FastRTPS manifest which can be fixed along the way.
- [x] Upload the archives under a new release in the `ros2` repo.
- [x] Announce the patch release with a name like `ardent-2018-02-xx`.

**Comment by wjwwood** [comment] 2018-01-31 04:43
I created a single Windows CI job to see if `rviz` even compiles in this setup:

- Windows: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4018)](http://ci.ros2.org/job/ci_windows/4018/)

**Comment by nuclearsandwich** [comment] 2018-01-31 17:10
> addressing a minor issue in the FastRTPS manifest which can be fixed along the way.

Addressed by https://github.com/ros2-gbp/fastrtps-release/pull/1

Noting for my own records that Fast-CDR hasn't changed since the ardent release so there's nothing there that needs bumping.

**Comment by wjwwood** [comment] 2018-02-01 00:00
We're tracking some issues with rviz's current state which we'd like to fix: https://github.com/ros2/rviz/pull/188#issuecomment-361993826

**Comment by wjwwood** [comment] 2018-02-05 22:17
I've finally finished updating all the CI machines in preparation for the release.

I'm going to update the rviz patch branch with some fixes that have been made since last week and then run CI again for this release. Then we're ready to make packages with the packaging job and do what ever level of testing we think is appropriate.

**Comment by wjwwood** [comment] 2018-02-05 22:18
I've also got a few staged changes to the wiki instructions, but we probably shouldn't change those until we have the patch release available (otherwise the existing binary would not work).

**Comment by wjwwood** [comment] 2018-02-06 00:51
I've updated the rviz pull request and so here's full CI on the updated CI machines:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3943)](http://ci.ros2.org/job/ci_linux/3943/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1061)](http://ci.ros2.org/job/ci_linux-aarch64/1061/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3273)](http://ci.ros2.org/job/ci_osx/3273/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4042)](http://ci.ros2.org/job/ci_windows/4042/)

**Comment by wjwwood** [comment] 2018-02-06 03:40
On macOS there was a false positive cmake warning created by interleaved output and the new cppcheck test failures which were introduced by update cppcheck on the macOS build machines:

http://ci.ros2.org/job/ci_osx/3273/testReport/junit/(root)/projectroot/cppcheck/

They were fixed in https://github.com/ros2/rclcpp/pull/436. Should that be back ported too or should we just live with it (since we'll not be running CI and nightlies on it anyways)?

----

Here's packaging jobs:

- Linux:
  - Fast-RTPS: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=64)](http://ci.ros2.org/job/ci_packaging_linux/64/)
  - OpenSplice: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=65)](http://ci.ros2.org/job/ci_packaging_linux/65/)
- Linux-aarch64:
  - Fast-RTPS: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=13)](http://ci.ros2.org/job/ci_packaging_linux-aarch64/13/)
  - OpenSplice: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=14)](http://ci.ros2.org/job/ci_packaging_linux-aarch64/14/)
- macOS:
  - Fast-RTPS: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_osx&build=23)](http://ci.ros2.org/job/ci_packaging_osx/23/)
  - OpenSplice: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_osx&build=24)](http://ci.ros2.org/job/ci_packaging_osx/24/)
- Windows:
  - Fast-RTPS: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=17)](http://ci.ros2.org/job/ci_packaging_windows/17/)
  - OpenSplice: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=18)](http://ci.ros2.org/job/ci_packaging_windows/18/)

**Comment by dirk-thomas** [comment] 2018-02-07 18:10
The previous builds used a gist which seems to not have a newer version of FastRTPS and doesn't include `ros_environment`. The following builds use the `ros2.repos` file from ros2/ros2#455.

* Linux
  * FastRTPS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=964)](http://ci.ros2.org/job/packaging_linux/964/)
  * OpenSplice [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=965)](http://ci.ros2.org/job/packaging_linux/965/)
* Linux-aarch64
  * FastRTPS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_linux-aarch64&build=330)](http://ci.ros2.org/job/packaging_linux-aarch64/330/)
  * OpenSplice [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_linux-aarch64&build=331)](http://ci.ros2.org/job/packaging_linux-aarch64/331/)
* macOS
  * FastRTPS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_osx&build=899)](http://ci.ros2.org/job/packaging_osx/899/)
  * OpenSplice [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_osx&build=900)](http://ci.ros2.org/job/packaging_osx/900/)
* Windows
  * FastRTPS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_windows&build=895)](http://ci.ros2.org/job/packaging_windows/895/)
  * OpenSplice [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_windows&build=896)](http://ci.ros2.org/job/packaging_windows/896/)

**Comment by dirk-thomas** [comment] 2018-02-07 18:11
> Should that be back ported too or should we just live with it (since we'll not be running CI and nightlies on it anyways)?

I would say we keep it as is now.

**Comment by dirk-thomas** [comment] 2018-02-07 21:11
When testing the fat archives and later the Debian packages we should check the following:

* check that the new environment variables `ROS_VERSION` and `ROS_DISTRO` are there
* check that `rviz2` starts and try adding / removing camera displays
* build custom `rosidl_interfaces` in an overlay workspace (see ros2/rcl_interfaces#31)
* run a couple of demos nodes for sanity checking

**Comment by nuclearsandwich** [comment] 2018-02-07 22:51
## Windows 🎐 

### Fast-RTPS archive
* ✅ New environment variables
* ✅ rviz2 starts
* ✅ camera displays can be added and removed (no actual camera data to publish)
* ⛔️  dummy_robot_bringup runs and tf animates once but then launched process appears to crash.
* ✅ talker/listener, service,clients run
* ⛔️ Cannot run msbuild to test overlay workspace

### OpenSplice archive 
* ✅ New environment variables
* ✅ rviz2 starts
* ✅ camera displays can be added and removed (no actual camera data to publish)
* ✅ rviz animates tf data when dummy_robot_bringup is launched
* ✅ talker/listener, service,clients run
* ⛔️ Cannot run msbuild to test overlay workspace

**Comment by Karsten1987** [comment] 2018-02-07 23:22
Fast-RTPS on OSX looks good on a first glance. 
Similar to the Windows report above, the TF tree doesn't animate correctly and times out.

**Comment by nuclearsandwich** [comment] 2018-02-07 23:26
Added a short wiki page for the necessary setup steps for releasing packages with bloom. https://github.com/ros2/ros2/wiki/Releasing-a-ROS-2-package-with-bloom/_history

**Comment by wjwwood** [comment] 2018-02-07 23:49
## macOS 

### OpenSplice archive 
* ✅ New environment variables
* ✅ `rviz2` starts
* ✅ camera displays can be added and removed (no actual camera data to publish)
* ✅ `rviz` animates `tf` data when `dummy_robot_bringup` is launched
* ✅ talker/listener, service/clients run
* ✅ Reproduced in older binary, fixed in new

As a side note, macOS is doing a pretty good job these days letting you know what the issue is:

```
% rviz2
dyld: Library not loaded: /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /tmp/ros2-osx/bin/rviz2
  Reason: Incompatible library version: rviz2 requires version 5.10.0 or later, but QtWidgets provides version 5.9.0
[1]    58108 abort      rviz2
```

and

```
% rviz2
dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /tmp/ros2-osx/bin/rviz2
  Reason: Incompatible library version: rviz2 requires version 23.0.0 or later, but libfreetype.6.dylib provides version 22.0.0
[1]    59719 abort      rviz2
```

**Comment by clalancette** [comment] 2018-02-07 23:55
I did some testing on ARM64.  I specifically tested the issues listed in https://github.com/ros2/ros2/issues/454#issuecomment-363911929, and all of those were fine.  I also did spot checking of client->server, pub/sub, cpp->py on Fast-RTPS and OpenSplice, which worked fine.

However, I did run into a bug when trying to cross Fast-RTPS and OpenSplice.  If I run an opensplice `ros2 run demo_nodes_cpp add_two_ints_server`, and a Fast-RTPS `ros2 run demo_nodes_cpp add_two_ints_client`, the client waits around forever.

**Comment by mikaelarguedas** [comment] 2018-02-08 00:22
> I did run into a bug when trying to cross Fast-RTPS and OpenSplice

cross vendor services are not supported, in ardent or master, so I'll say it's expected

**Comment by clalancette** [comment] 2018-02-08 00:23
> cross vendor services are not supported, in ardent or master, so I'll say it's expected

Great, sounds fine then.  No other bugs to report.

**Comment by nuclearsandwich** [comment] 2018-02-08 00:37
Bloom release PRs are starting to roll in to ros2/rosdistro. My intention is to merge them all at once after https://github.com/ros2/ros2/pull/455 is reviewed and merged.

**Comment by nuclearsandwich** [comment] 2018-02-09 17:26
Debian packages are ready in the ros2 testing repository. Packaging jobs are queued for fat archives.

## MacOS
##### Fast-RTPS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_osx&build=903)](http://ci.ros2.org/job/packaging_osx/903/)
##### OpenSplice [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_osx&build=904)](http://ci.ros2.org/job/packaging_osx/904/) (queued)

## Ubuntu Xenial

##### Fast-RTPS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=968)](http://ci.ros2.org/job/packaging_linux/968/) (queued)

##### OpenSplice [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=969)](http://ci.ros2.org/job/packaging_linux/969/) (queued)

## Windows

##### Fast-RTPS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_windows&build=899)](http://ci.ros2.org/job/packaging_windows/899/)
##### OpenSplice [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_windows&build=900)](http://ci.ros2.org/job/packaging_windows/900/) (queued)

**Comment by clalancette** [comment] 2018-02-09 18:17
I tested the ARM64 debs, using the basic recipe in https://github.com/ros2/ros2/issues/454#issuecomment-363911929 .  All seemed well there, including a pub/sub and a service test (I couldn't test rviz2, but I think that is OK).

**Comment by dirk-thomas** [comment] 2018-02-09 18:19
Same results for me when I tried them yesterday late afternoon. Can someone please test `rviz2`.

**Comment by nuclearsandwich** [comment] 2018-02-09 18:32
> Same results for me when I tried them yesterday late afternoon. Can someone please test rviz2.

rviz2 dummy robot bringup worked fine with both opensplice and fastrtps.

**Comment by mikaelarguedas** [comment] 2018-02-09 18:34
tested rviz2 from binaries, it launches fine and doesnt crash on camera plugin load/unload

the dummy_robot example didnt work first time with the tfs being received only once and then fading away. Worked fine the second time

**Comment by dirk-thomas** [comment] 2018-02-09 22:22
> I've also got a few staged changes to the wiki instructions, but we probably shouldn't change those until we have the patch release available (otherwise the existing binary would not work).

@wjwwood Can you push these changes and reference them here.

**Comment by wjwwood** [comment] 2018-02-09 23:14
I've pushed the changes:

- https://github.com/ros2/ros2/wiki/OSX-Install-Binary/_compare/6801c07e868dc6919eecb80dfa58d097135479ae...b67511b9323d016e0993e5eb2a32f52b50311208
- https://github.com/ros2/ros2/wiki/OSX-Development-Setup/_compare/a8369e7f20d5bb4e361be66de51e7107c8bdcbbe...1656b84e891c8bb39aa123cf825b2758be0a4e87
- https://github.com/ros2/ros2/wiki/Windows-Development-Setup/_compare/90f9e52734ef0e25d8a9319556c1412032d59926...8ac1d8bd2c887383606e2bbfad1055fc6532da8f

**Closed** 2018-02-12 18:00 UTC
Labels: in progress
