### ISSUE TITLE
rmw_get_node_names should provide more up-to-date information

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#371] opened 2017-06-26 23:27 UTC
Currently `rmw_get_node_names` also returns nodes which have already been terminated. This is currently the case for both rmw impl. `rmw_fastrtps_cpp` as well as `rmw_connext_cpp`.

Maybe there is a way to "ensure" that nodes which are being terminated try to let other participants know being terminated. This also depends on the long term plan to tie node names to participants or now...

**Comment by dhood** [comment] 2017-09-15 18:29
this might have been caused by the way we were terminating nodes without giving them a chance to shutdown cleanly, which has been resolved in https://github.com/ros2/ros2cli/pull/50.

Topics and nodes can still be listed after shutdown if nodes don't shutdown cleanly (e.g. sigkill) but I believe the initial ticket was referring to "general use", right @dirk-thomas ?

**Comment by dirk-thomas** [comment] 2017-09-15 18:31
I only tried it with FastRTPS recently but for `demo_nodes_cpp` / `demo_nodes_py` `talker` / `listener` I can't reproduce the problem anymore. After stopping either of the sides the node is not listed anymore. And after stopping both the topic is gone too.

**Comment by dhood** [comment] 2017-09-26 17:42
That is the behaviour that I saw as well, provided you don't sigkill, so it seems this is good to be closed now

**Closed** 2017-09-26 17:48 UTC
