### ISSUE TITLE
All documents published online should carry a timestamp (and version number?)

### ISSUE THREAD

**Issue by balanco** [ros2/ros2#1193] opened 2021-09-30 14:30 UTC
## Bug report

**Required Info:**

- Operating System:
  (does not apply)
- Installation type:
  (does not apply)
- Version or commit hash:
  (does not apply)
- DDS implementation:
  (does not apply)
- Client library (if applicable):
  (does not apply)

#### Steps to reproduce issue

Load any published reference document, e.g., such high-visibility, high-impact documents as "Why ROS 2?"
[https://design.ros2.org/articles/why_ros2.html] (visited 2021-09-30T16:27:00CEST).

#### Expected behavior

Display of the publication date, as a key piece of meta-information(in some consistent format and location across all publications)

#### Additional information

----

**Comment by clalancette** [comment] 2021-09-30 14:31
This is a duplicate of https://github.com/ros2/design/issues/320, so closing

**Closed by clalancette** 2021-09-30 14:31 UTC
