### ISSUE TITLE
Unhandled Terminate w/ Services Over Wifi Network

### ISSUE THREAD

**Issue by connoranderson** [ros2/ros2#1253] opened 2022-04-05 18:02 UTC
Relates to https://github.com/ros2/ros2/issues/1017

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - Latest galactic
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
I'm able to reproduce this intermittently both in CI as well as on real wireless devices, and it does not reproduce on cyclonedds. To replicate the behavior we see in real life, I issue service calls quickly over a WIFI network.

On machine 1
`ros2 run demo_nodes_cpp add_two_ints_server`

On machine 2, connected via WIFI to machine 1
`seq 1 25 | parallel -j 25 ros2 run demo_nodes_cpp add_two_ints_client &`

It's not 100% of the time, but using this setup over a wifi-based network, I'm able to reproduce the exact error we see in the wild.

#### Expected behavior

No terminations

#### Actual behavior

`
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError' what(): failed to send response: client will not receive response, at /tmp/binarydeb/ros-galactic-rmw-fastrtps-shared-cpp-5.0.1/src/rmw_response.cpp:129, at /tmp/binarydeb/ros-galactic-rcl-3.1.2/src/rcl/service.c:287
`

#### Additional information

Doesn't break on CycloneDDS. Doesn't break when run locally with both nodes on the same host.

**Comment by fujitatomoya** [comment] 2022-04-13 21:57
using 2 Raspi4 and docker `ros:rolling` image with host network, i am unable to reproduce this issue so far.

Just FYI, followings are script and output. I've tried 20 times, but the problem cannot be observed.

```bash
root@raspi4-2:~# cat test.sh
#!/bin/bash

for i in {1..25}
do
    ros2 run demo_nodes_cpp add_two_ints_client &
done

root@raspi4-2:~# ./test.sh
root@raspi4-2:~# [INFO] [1649886877.729114954] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886877.893488932] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886878.697137477] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886878.820897274] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886878.861090053] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886878.868279131] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886878.956127614] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886879.306310491] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886879.315705430] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886879.429241539] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886879.684340985] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886879.763497558] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886879.873621080] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886879.894847409] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886879.957191913] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886880.053126297] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886880.096637275] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886880.148100989] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886880.549728597] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886880.660386206] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886880.787165299] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886880.823617050] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886880.963625443] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886881.018721777] [add_two_ints_client]: Result of add_two_ints: 5
[INFO] [1649886881.114124686] [add_two_ints_client]: Result of add_two_ints: 5
```

**Comment by fujitatomoya** [comment] 2022-04-13 21:58
could be related to https://github.com/ros2/rmw_fastrtps/issues/597 ?

**Comment by connoranderson** [comment] 2022-04-13 22:09
Hi @fujitatomoya,

A few thoughts:

1. Have you tried using `ros:galactic`? This is the docker image I used to get the above logs.
2. I noticed you're using a `for` loop for the client calls, but essentially that is running all requests in series. In our application, we do sometimes send multiple, asynchronous requests to a service (admittedly not 25 but you get the idea) so that is what the `parallel` command is doing in my example. 25 is an arbitrary number that started showing the terminate, but we've seen it happen less frequently at lower rates.

**Comment by connoranderson** [comment] 2022-04-13 22:12
> could be related to [ros2/rmw_fastrtps#597](https://github.com/ros2/rmw_fastrtps/issues/597) ?

It might be! I've not seen that error message before, but if the assertion was introduced after `galactic`, then it's very possible.

**Comment by fujitatomoya** [comment] 2022-04-13 22:30
> but essentially that is running all requests in series.

the process is instantiated as background. so i think requests are happening in parallel.

**Comment by connoranderson** [comment] 2022-04-13 23:31
> the process is instantiated as background. so i think requests are happening in parallel.

Ah yes, my bad. This should be identical then (minus the different ROS version)

**Comment by EduPonz** [comment] 2022-04-18 09:05
This is because of the handling on [this return](https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_shared_cpp/src/rmw_response.cpp#L129) in upper layers. As explained in [here](https://github.com/ros2/rmw_fastrtps/pull/418), there is a data race in service discovery in ROS 2. The fact that the exception is not happening with other implementations is that they return OK instead of TIMEOUT, so the race does happen, it's just not detected. From my point of view upper layers should handle the TIMEOUT different from the error, but that is currently not the case. The race is as follows:

1. RPC is handled using a pair of topics, one for the request and another one for the response, which implies 4 endpoints:
    1. Request writer (client side)
    2. Request reader (server side)
    3. Response writer (server side)
    4. Response reader (client side)
2. Request writer discovers request reader
3. Request reader discovery request writer
4. Client sends request
5. Server computes response
6. Server uses response writer to send response, but the response writer is yet to discover the response reader.
7. [Response writer waits 100 ms](https://github.com/ros2/rmw_fastrtps/blob/f9eb927a5b9fec3e276035a799fcacb9815db319/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp#L139-L155) for the reader to become available
8. Server's action of sending the response [times out](https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_shared_cpp/src/rmw_response.cpp#L130)
9. [RCL handles this as an error and throws execption](https://github.com/ros2/rcl/blob/galactic/rcl/src/rcl/service.c#L284-L291).

The thing is that [rmw_send_response documentation](https://github.com/ros2/rmw/blob/d778df84af42cdbc5458361a2fe220317494634c/rmw/include/rmw/rmw.h#L2421-L2428) does not specify what to do in this specific case. rmw_fastrtps took the approach of notifying what's happening through a different return code, while other implementations simply return OK. Mind that a subsequent call to the service may perfectly work, since discovery would most likely be completed by then.

**Comment by connoranderson** [comment] 2022-05-06 19:20
@EduPonz thanks for the detailed reply. All this is outside my wheelhouse, but what's the best way to get attention to this class of issue?

Also, what's the preferred way to avoid the termination here?

**Comment by EduPonz** [comment] 2022-05-11 06:03
> what's the best way to get attention to this class of issue?

I'd like to defer to @fujitatomoya of @clalancette for that

> Also, what's the preferred way to avoid the termination here?

You could run within `try`-`catch` and maybe try to call the service again, although I don't think catching all `RCLError` is ideal.

**Comment by fujitatomoya** [comment] 2022-05-11 17:36
> The fact that the exception is not happening with other implementations is that they return OK instead of TIMEOUT, so the race does happen, it's just not detected.

i think it does detect the TIMEOUT and return to TIMEOUT to rcl as well.
`rmw_cyclonedds` also waits the reader for 100ms and if it gets `client_present_t::MAYBE`, RMW_RET_TIMEOUT will be returned.

https://github.com/ros2/rmw_cyclonedds/blob/00bf8ad0da244c55578c4bc63d32fc0d918cb7cb/rmw_cyclonedds_cpp/src/rmw_node.cpp#L4427-L4439

but @EduPonz is right, this is about timing and racy condition ends up with `TIMEOUT` eventually.

atm, I am not sure how we can handle `TIMEOUT` on service server side during sending the response back to client. any thought?

**Comment by clalancette** [comment] 2022-05-26 17:21
Reading the comments here, I think there is ambiguity in the RMW layer on how the implementations should respond.  But there also may be a bug in how rcl handles this situation.  I've assigned it to both @EduPonz (for any advice on the Fast-DDS side), and one of the `rcl` maintainers for advice on that side.

**Comment by ivanpauno** [comment] 2022-05-30 12:56
> atm, I am not sure how we can handle TIMEOUT on service server side during sending the response back to client. any thought?

rcl should return `RCL_RET_TIMEOUT` in this case ([here](https://github.com/ros2/rcl/blob/master/rcl/src/rcl/service.c#L311-L315)), and rclcpp should throw an specific exception so it can be handled.

It's not great, I think the API should be better, but it's something.

**Comment by EduPonz** [comment] 2022-06-01 05:13
> rcl should return `RCL_RET_TIMEOUT` in this case ([here](https://github.com/ros2/rcl/blob/master/rcl/src/rcl/service.c#L311-L315)), and rclcpp should throw an specific exception so it can be handled.

I agree with this. Having a TIMEOUT return may end up being useful in the future, specially when adding timeout parameters to blocking functions to increase real time capabilities.

**Comment by vale** [comment] 2023-03-17 13:07
Is it possible to provide error handling for the RCLCPP exception within a node or will it be necessary to patch ros2 or rmw_fastrtps to get rid of theses terminations?

**Comment by fujitatomoya** [comment] 2023-03-17 20:19
@vale unfortunately no, currently no such feature available. as we discussed before, it would be probably best that `rcl_send_request` should return TIMEOUT, so that rclcpp should throw an specific exception so it can be handled.

**Comment by fujitatomoya** [comment] 2023-04-13 06:26
@agoeckner 

rmw_cyclonedds also returns `TIMEOUT` when the same situation happens. so technically this problem could be observed too.

https://github.com/ros2/rmw_cyclonedds/blob/76572ebf1032f359ed302d7017471a295738fa1e/rmw_cyclonedds_cpp/src/rmw_node.cpp#L4541-L4542

> Is there any word on a solution for FastRTPS?

Currently no. not only for rmw_fastrtps but other rmw implementations AFAIK.

**Comment by agoeckner** [comment] 2023-04-13 14:54
> @agoeckner
> 
> rmw_cyclonedds also returns `TIMEOUT` when the same situation happens. so technically this problem could be observed too.
> 
> https://github.com/ros2/rmw_cyclonedds/blob/76572ebf1032f359ed302d7017471a295738fa1e/rmw_cyclonedds_cpp/src/rmw_node.cpp#L4541-L4542
> 
> > Is there any word on a solution for FastRTPS?
> 
> Currently no. not only for rmw_fastrtps but other rmw implementations AFAIK.

Strangely, I experience this issue only when using FastRTPS. Is there different between FastRTPS and CycloneDDS (perhaps default QoS settings) that would cause this discrepancy?

**Comment by fujitatomoya** [comment] 2023-04-13 16:35
I believe this is related to buildin discovery process in DDS implementation.

**Comment by elcritch** [comment] 2023-04-21 21:41
We're having this issue occur when using Python clients. 

> > i think it does detect the TIMEOUT and return to TIMEOUT to rcl as well.
> rmw_cyclonedds also waits the reader for 100ms and if it gets client_present_t::MAYBE, RMW_RET_TIMEOUT will be returned.

> Strangely, I experience this issue only when using FastRTPS. Is there something different between FastRTPS and CycloneDDS (perhaps default QoS settings) that would cause this discrepancy?

Maybe that's a difference? 

What's the rationale of killing the entire RCL process when this occurs? It's not clear to me if a race condition in the discovery service should bring the whole system down. Is there a way to restart the affected services and restart just them?

**Comment by fujitatomoya** [comment] 2023-04-21 22:13
> We're having this issue occur when using Python clients.

the error comes from rcl/rmw that means any client rclcpp, rclpy or other community packages relies on rcl possibly have this problem, if client generates exception on this error. (AFAIS, rclcpp and rclpy generates exception.)

> What's the rationale of killing the entire RCL process when this occurs?

good point, i was thinking that it should print the error says `response message could not be sent to client` if time out happens but generating the exception. (this time out means client is not there yet.) So that this service server still can be running after the timeout error.

> Is there a way to restart the affected services and restart just them?

i think both rclcpp and rclpy, this process is handled by executor thread once executable service is ready. that means probably we can protect `spin` with `try & catch(except)` statement in the application, which is not sophisticated but could work.

**Comment by royito55** [comment] 2023-06-20 16:38
This happens to me often with Fast-DDS as well. It wouldn't be an issue except that this causes nodes to die right after

**Comment by agoeckner** [comment] 2023-06-20 16:39
> This happens to me often with Fast-DDS as well. It wouldn't be an issue except that this causes nodes to die right after

Exactly. This should *never* result in an unhandleable node failure.

**Comment by fujitatomoya** [comment] 2023-06-20 17:22
@royito55 @agoeckner 

> i think both rclcpp and rclpy, this process is handled by executor thread once executable service is ready. that means probably we can protect spin with try & catch(except) statement in the application, which is not sophisticated but could work.

how about adding this to the application code for now? just sharing the possible work-around?

**Comment by agoeckner** [comment] 2023-06-20 17:47
No, that does not work, as this error can even occur in packages which have been distributed as binaries. Modifying every ROS 2 package isn't a good solution.

**Comment by longjie0723** [comment] 2023-06-23 10:21
Hi, I recently noticed that this problem also occurs in our program and have come across this issue.

- I am able to reproduce this using the add_two_ints server and client, just like in the original report.
- Both the server and clients are running on a single machine, so it is not related to WiFi (the title should be improved).
- When using CycloneDDS, the problem never occurs.

I'm eager to receive updates on this matter. Thank you.

**Comment by EduPonz** [comment] 2023-06-23 12:29
We have been recently investigating this issue. While we provide a proper fix, may you try testing forcing the communications to use the UPD transport? You could use this XML (just make sure to `export FASTRTPS_DEFAULT_PROFILES_FILE=<path_to_xml_file>` in all terminals). We have been testing in Humble and where not able to reproduce the issue this way:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<dds>
    <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles" >
        <transport_descriptors>
            <!-- Create a custom transport descriptor -->
            <transport_descriptor>
                <transport_id>custom_udpv4_transport</transport_id>
                <type>UDPv4</type>
            </transport_descriptor>
        </transport_descriptors>
        <participant profile_name="participant_profile" is_default_profile="true">
            <rtps>
                <!-- Disable builtin transports -->
                <useBuiltinTransports>false</useBuiltinTransports>
                <!-- Enable custom transport -->
                <userTransports>
                    <transport_id>custom_udpv4_transport</transport_id>
                </userTransports>
            </rtps>
        </participant>
    </profiles>
</dds>
```

**Comment by longjie0723** [comment] 2023-07-01 05:53
@EduPonz Hi, thank you for your investigating. I tried with your profile file, but same error happens.

On terminal1:
```
$ export FASTRTPS_DEFAULT_PROFILES_FILE=`pwd`/config.xml
$ ros2 run demo_nodes_cpp add_two_ints_server
```

On terminal2:
```
$ export FASTRTPS_DEFAULT_PROFILES_FILE=`pwd`/config.xml
$ for i in `seq 1 50`; do ros2 run demo_nodes_cpp add_two_ints_client & done
```

Then the server is aborted as:
```
[INFO] [1688189767.677087363] [add_two_ints_server]: Incoming request
a: 2 b: 3
[INFO] [1688189767.710754893] [add_two_ints_server]: Incoming request
a: 2 b: 3
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to send response: client will not receive response, at ./src/rmw_response.cpp:149, at ./src/rcl/service.c:314
[ros2run]: Aborted
```
Actually the number of accessing clients  is a matter. When I reduced it to 20, error doesn't happens. 25 clients as in the original post, sometimes I got the error.

Using CycloneDDS, this error doesn't happen even the number of the clients is 50.

I confirmed above results using Humble on Ubuntu 22.04(native) and WSL2.

**Comment by fujitatomoya** [comment] 2023-07-05 04:44
@longjie0723 thanks for sharing the verification details.

after all, this problem could happen eventually if there is racy condition to establish the connection between server and client with different topics. the following PRs can avoid generating the exception on server side if `failed to send response` happens.

if you could try out those PRs, that would be really appreciated.

**Comment by agoeckner** [comment] 2023-07-06 21:20
@fujitatomoya, did you intend to link some PRs here? I don't see them.

**Comment by PYRET1C** [comment] 2023-07-14 06:56
Hello guys, i am facing the same error.
How can we handle this?
i have tried putting the entire main function in the try-except statement but it still crashes.
Any suggestions..?

**Comment by brennand** [comment] 2023-08-07 12:07
> We have been recently investigating this issue. While we provide a proper fix, may you try testing forcing the communications to use the UPD transport? You could use this XML (just make sure to `export FASTRTPS_DEFAULT_PROFILES_FILE=<path_to_xml_file>` in all terminals). We have been testing in Humble and where not able to reproduce the issue this way:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" ?>
> <dds>
>     <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles" >
>         <transport_descriptors>
>             
>             <transport_descriptor>
>                 <transport_id>custom_udpv4_transport</transport_id>
>                 <type>UDPv4</type>
>             </transport_descriptor>
>         </transport_descriptors>
>         <participant profile_name="participant_profile" is_default_profile="true">
>             <rtps>
>                 
>                 <useBuiltinTransports>false</useBuiltinTransports>
>                 
>                 <userTransports>
>                     <transport_id>custom_udpv4_transport</transport_id>
>                 </userTransports>
>             </rtps>
>         </participant>
>     </profiles>
> </dds>
> ```

Hello, This fixed this "Bug" for me. Thanks

**Comment by brennand** [comment] 2023-08-07 12:23
> We have been recently investigating this issue. While we provide a proper fix, may you try testing forcing the communications to use the UPD transport? You could use this XML (just make sure to `export FASTRTPS_DEFAULT_PROFILES_FILE=<path_to_xml_file>` in all terminals). We have been testing in Humble and where not able to reproduce the issue this way:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" ?>
> <dds>
>     <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles" >
>         <transport_descriptors>
>             
>             <transport_descriptor>
>                 <transport_id>custom_udpv4_transport</transport_id>
>                 <type>UDPv4</type>
>             </transport_descriptor>
>         </transport_descriptors>
>         <participant profile_name="participant_profile" is_default_profile="true">
>             <rtps>
>                 
>                 <useBuiltinTransports>false</useBuiltinTransports>
>                 
>                 <userTransports>
>                     <transport_id>custom_udpv4_transport</transport_id>
>                 </userTransports>
>             </rtps>
>         </participant>
>     </profiles>
> </dds>
> ```

I've tried this and still get this error.  This happens randomly in my main ROS2:humble program, using the above xml config.  But it also just happened in RVIZ2 sending a desired goal:

```
[INFO]: Message Filter dropping message: frame 'base_scan' at time 961.820 for reason 'the timestamp on the message is earlier than all the data in the transform cache
[INFO]: Setting estimate pose: Frame:map, Position(-4.01042, -3.88176, 0), Orientation(0, 0, -0.719096, 0.694911) = Angle: -1.605
[INFO]: Setting estimate pose: Frame:map, Position(-3.91969, -4.65493, 0), Orientation(0, 0, -0.938262, 0.345925) = Angle: -2.43514
Start navigation
[INFO]: NavigateToPose will be called using the BT Navigator's default behavior tree.
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to send response: client will not receive response, at ./src/rmw_response.cpp:149, at ./src/rcl/service.c:314
Aborted (core dumped)
```

This only just started to happen when I setup and installed ROS2 via docker on a brand new laptop. But its the same code base and 100% same docker build script.  The Nav stack gets the request and starts to navigate to the goal.

**Comment by agoeckner** [comment] 2023-08-18 20:47
Thanks for the work on this @fujitatomoya. Is this resolved now?

If so, do you know when the fix will be released to Humble binaries?

**Comment by fujitatomoya** [comment] 2023-08-19 00:03
this has been addressed with rolling but humble nor iron. i was going to resolve this once all backports are completed to track the issue.

> If so, do you know when the fix will be released to Humble binaries?

I am not sure... sorry @audrow @clalancette any idea?

**Comment by fujitatomoya** [comment] 2023-09-01 15:31
To all, thanks for sharing information and contribution. all related fixes including backports have been completed.

@clalancette can you close this?

**Closed** 2023-09-01 15:35 UTC

**Comment by agoeckner** [comment] 2023-09-08 19:02
@clalancette do you know when this will be released to Humble binaries?

**Comment by clalancette** [comment] 2023-09-08 19:05
I don't know the schedule for the next Humble patch release.  @audrow any thoughts?

**Comment by audrow** [comment] 2023-09-14 17:08
> I don't know the schedule for the next Humble patch release. @audrow any thoughts?

I'll start a patch next week 👍

**Comment by tony-p** [comment] 2023-12-01 11:36
(For late comers here) In order to reduce timeouts occurring on service calls with fastdds TCP, disabling the nagle algorithm has helped us. In a custom dds profile for TCP set `enable_tcp_nodelay` to true.

```xml
<transport_descriptor>
            <transport_id>CustomTcpTransport</transport_id>
            <type>TCPv4</type>
            <enable_tcp_nodelay>true</enable_tcp_nodelay>
        </transport_descriptor>
```

**Comment by Procession6** [comment] 2025-02-01 21:36
I unlocked the answer https://stackdev.space/questions/opt-for-utilizing-the-constructor-with-parameters-in-a-mfc-c-class-member-variable-declaration
