### ISSUE TITLE
Pytest segfault on Cyclone DDS using @pytest.mark.parametrize

### ISSUE THREAD

**Issue by blacksoul000** [ros2/ros2#1018] opened 2020-08-27 13:59 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - foxy latest release
- DDS implementation:
  - Cyclone DDS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
```
import pytest

import rclpy
from rclpy.node import Node


class TestController(object):

    ctrl = None

    def setup_method(self, _):
        rclpy.init()
        self.ctrl = Node('test')

    def teardown_method(self, _):
        self.ctrl.destroy_node()
        rclpy.shutdown()

    @pytest.mark.parametrize(('idx'), range(0, 100))
    def test_000_setup(self, idx):
        assert True
```

#### Expected behavior
All tests passed

#### Actual behavior
```
platform linux -- Python 3.8.2, pytest-6.0.1, py-1.9.0, pluggy-0.13.0
rootdir: /tmp/11
plugins: ament-pep257-0.9.5, ament-xmllint-0.9.5, launch-testing-ros-0.10.2, ament-flake8-0.9.5, launch-testing-0.10.2, ament-lint-0.9.5, ament-copyright-0.9.5, hypothesis-5.26.0, cov-2.8.1, colcon-core-0.6.0, mock-1.10.4
collected 100 items 

my_test.py ........................................................Fatal Python error: Aborted

Thread 0x00007fe353e1b740 (most recent call first):
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/node.py", line 164 in __init__
  File "/tmp/11/my_test.py", line 13 in setup_method
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/python.py", line 674 in _call_with_optional_argument
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/python.py", line 770 in xunit_setup_method_fixture
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/fixtures.py", line 915 in call_fixture_func
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/fixtures.py", line 1117 in pytest_fixture_setup
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/fixtures.py", line 1062 in execute
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/fixtures.py", line 683 in _compute_fixture_value
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/fixtures.py", line 601 in _get_active_fixturedef
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/fixtures.py", line 581 in getfixturevalue
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/fixtures.py", line 568 in _fillfixtures
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/python.py", line 1573 in setup
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/runner.py", line 432 in prepare
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/runner.py", line 141 in pytest_runtest_setup
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/runner.py", line 247 in <lambda>
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/runner.py", line 294 in from_call
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/runner.py", line 246 in call_runtest_hook
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/runner.py", line 207 in call_and_report
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/runner.py", line 111 in runtestprotocol
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/runner.py", line 100 in pytest_runtest_protocol
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/main.py", line 321 in pytest_runtestloop
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/main.py", line 296 in _main
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/main.py", line 240 in wrap_session
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/main.py", line 289 in pytest_cmdline_main
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 157 in main
  File "/home/user/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 180 in console_main
  File "/home/user/.local/bin/pytest", line 8 in <module>
Aborted (core dumped)
```

#### Additional information
With Fast-RTPS works fine.
With range(0, 56) works fine =)

Following code works fine even with Cyclone DDS:
```
import pytest

import rclpy
from rclpy.node import Node


class TestController(object):

    def setup_method(self, _):
        rclpy.init()

    def teardown_method(self, _):
        rclpy.shutdown()

    @pytest.mark.parametrize(('idx'), range(0, 100))
    def test_000_setup(self, idx):
        for i in range(0, 100):
            ctrl = Node('test_node')
            ctrl.destroy_node()
        assert True
```

**Comment by clalancette** [comment] 2022-02-03 14:13
This looks like it is fixed in the latest code; at least, the original reproducer no longer crashes.  So I'm going to close this out.

**Closed by clalancette** 2022-02-03 14:13 UTC
Labels: bug, CycloneDDS
