### ISSUE TITLE
Unable to find rclcpp in windows using nightly build

### ISSUE THREAD

**Issue by koonpeng** [ros2/ros2#1068] opened 2020-12-08 13:19 UTC
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - binary
- Version or commit hash:
  - nightly
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
in CMakeLists.txt
```
find_package(rclcpp)
```

#### Expected behavior
rclcpp is found

#### Actual behavior
got error
```
  Imported target "rclcpp::rclcpp" includes non-existent path
    "C:/ci/ws/install/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
```

#### Additional information

Tested using https://ci.ros2.org/view/packaging/job/packaging_windows/lastSuccessfulBuild/artifact/ws/ros2-package-windows-AMD64.zip, was working with foxy release patch 3.

This also happens in several other packages

```
koonpeng@koonpeng-Home:~/Downloads/ros2-windows/share$ grep -r 'ci/ws'
rviz_visual_testing_framework/cmake/rviz_visual_testing_frameworkExport.cmake:  INTERFACE_INCLUDE_DIRECTORIES "C:/ci/ws/install/src/gtest_vendor/include;${_IMPORT_PREFIX}/include"
rcl/cmake/rclExport.cmake:  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/ci/ws/install/include"
rclcpp/cmake/rclcppExport.cmake:  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/ci/ws/install/include"
rviz_rendering/cmake/rviz_renderingExport.cmake:  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/ProgramData/chocolatey/lib/eigen/include;C:/ci/ws/install/opt/rviz_assimp_vendor/include;${_IMPORT_PREFIX}/include"
rviz_rendering/cmake/rviz_renderingExport.cmake:  INTERFACE_LINK_LIBRARIES "rviz_ogre_vendor::OgreMain;rviz_ogre_vendor::OgreOverlay;Qt5::Widgets;ament_index_cpp::ament_index_cpp;resource_retriever::resource_retriever;C:/ci/ws/install/opt/rviz_assimp_vendor/lib/assimp-vc140-mt.lib"
rviz_common/cmake/rviz_commonExport.cmake:  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/ci/ws/install/opt/rviz_assimp_vendor/include;${_IMPORT_PREFIX}/include"
rviz_common/cmake/rviz_commonExport.cmake:  INTERFACE_LINK_LIBRARIES "rviz_ogre_vendor::OgreMain;rviz_ogre_vendor::OgreOverlay;rviz_rendering::rviz_rendering;Qt5::Widgets;geometry_msgs::geometry_msgs__rosidl_generator_c;geometry_msgs::geometry_msgs__rosidl_typesupport_introspection_c;geometry_msgs::geometry_msgs__rosidl_typesupport_c;geometry_msgs::geometry_msgs__rosidl_generator_cpp;geometry_msgs::geometry_msgs__rosidl_typesupport_introspection_cpp;geometry_msgs::geometry_msgs__rosidl_typesupport_cpp;pluginlib::pluginlib;rclcpp::rclcpp;resource_retriever::resource_retriever;sensor_msgs::sensor_msgs__rosidl_generator_c;sensor_msgs::sensor_msgs__rosidl_typesupport_introspection_c;sensor_msgs::sensor_msgs__rosidl_typesupport_c;sensor_msgs::sensor_msgs__rosidl_generator_cpp;sensor_msgs::sensor_msgs__rosidl_typesupport_introspection_cpp;sensor_msgs::sensor_msgs__rosidl_typesupport_cpp;std_msgs::std_msgs__rosidl_generator_c;std_msgs::std_msgs__rosidl_typesupport_introspection_c;std_msgs::std_msgs__rosidl_typesupport_c;std_msgs::std_msgs__rosidl_generator_cpp;std_msgs::std_msgs__rosidl_typesupport_introspection_cpp;std_msgs::std_msgs__rosidl_typesupport_cpp;tf2::tf2;tf2_geometry_msgs::tf2_geometry_msgs;tf2_ros::tf2_ros;tf2_ros::static_transform_broadcaster_node;message_filters::message_filters;urdf::urdf;yaml-cpp;C:/ci/ws/install/opt/rviz_assimp_vendor/lib/assimp-vc140-mt.lib"
rcl_lifecycle/cmake/rcl_lifecycleExport.cmake:  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/ci/ws/install/include"
```

**Comment by hidmic** [comment] 2020-12-14 19:27
I took a brief look, and I might be completely off tracks, but I suspect an interaction between `tracetools` and (non)modern CMake support in `ament_target_dependencies()`. Since `tracetools` does not export targets on `Win32` by default, the exported `_INCLUDE_DIRS` variable containing a `${tracetools_DIR}/../../../include` path gets picked up.

If my assessment is correct, `tracetools` should be exporting an `INTERFACE` target instead and we have a problem with `ament_target_dependencies()` and relocatable packages.

**Comment by clalancette** [comment] 2022-02-03 20:36
Since this very much looks like a duplicate of https://github.com/ros2/rclcpp/issues/1688, I'm going to close this one out.

**Closed by clalancette** 2022-02-03 20:36 UTC
Labels: bug
