### ISSUE TITLE
Hardcoded absolute path in `export_builtin_interfaces__rosidl_generator_pyExport.cmake` leads to failures during cross-compilation

### ISSUE THREAD

**Issue by nikoskoukis-slamcore** [ros2/ros2#1437] opened 2023-06-08 12:05 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - Humble binary installation
- DDS implementation:
  - Fast-RTPS (default humble DDS version)

### Description

My goal is to successfully cross-compile for ARM 64 a ROS 2 package against ROS 2 humble. This is not the standard cross-compilation procedure described in [docs.ros.org](https://docs.ros.org/en/foxy/How-To-Guides/Cross-compilation.html#cross-compiling-against-a-pre-built-ros-2).

Instead, I have a docker container running Ubuntu 22.04 on a Ubuntu22.04, amd64 host. Inside there I'm spawning an arm64 chroot and I'm specifying the chroot path as part of my cross-compilation instructions to `colcon`.

This is roughly what my colcon CLI looks like:

```sh
colcon build \
    --cmake-args 
    -DCMAKE_TOOLCHAIN_FILE=/armv8.toolchain -DPYTHON_SOABI=cpython-310-aarch64-linux-gnu \
    -DCMAKE_PREFIX_PATH=/home/berger/rootfs/opt/ros/humble
```

The toolchain file is not super relevant but it does specify the same `CMAKE_FIND_ROOT_PATH_MODE_*` vars as the cross-compilation page on ros.org

```cmake
set(CMAKE_SYSROOT $ENV{HOME}/rootfs)

...

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```

The ROS 2 package I'm compiling - `slamcore_msgs`  defines a series of custom messages.

It tries to compile these messages with the following cmake code:

```cmake
# generate services / messages
rosidl_generate_interfaces(${PROJECT_NAME}
  ${MSGS_SOURCES}
  DEPENDENCIES builtin_interfaces geometry_msgs std_msgs)

ament_export_dependencies(rosidl_default_runtime)
ament_package()
```

Executing `colcon` produces output like the following:

```
--- stderr: slamcore_msgs
gmake[2]: *** No rule to make target '/usr/lib/aarch64-linux-gnu/libpython3.10.so', needed by 'rosidl_generator_py/slamcore_msgs/libslamcore_msgs__rosidl_generator_py.so'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:475: CMakeFiles/slamcore_msgs__rosidl_generator_py.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
```

You'll notice that `/usr/lib/aarch64-linux-gnu/libpython3.10.so` falls outside the rootfs I've specified as SYSROOT. Running `colcon --cmake-args --trace ...`  shows that this path is hardcoded in an auto-generated file that comes with the `ros-humble-builtin-interfaces` deb package

```
/opt/ros/humble/share/builtin_interfaces/cmake/export_builtin_interfaces__rosidl_generator_pyExport.cmake:57
```

```
...
# Create imported target builtin_interfaces::builtin_interfaces__rosidl_generator_py
  add_library(builtin_interfaces::builtin_interfaces__rosidl_generator_py SHARED IMPORTED)
  
set_target_properties(builtin_interfaces::builtin_interfaces__rosidl_generator_py PROPERTIES
  INTERFACE_LINK_LIBRARIES "builtin_interfaces::builtin_interfaces__rosidl_generator_c;/usr/lib/aarch64-linux-gnu/libpython3.10.so;builtin_interfaces::builtin_interfaces__rosidl_typesupport_c"
)
...
```

Hardcoding absolute paths in a function that may be called during cross-compiling as in this case seems like a bug to me and I think this is the reason the cross-compilation of my package fails.

The `export_builtin_interfaces__rosidl_generator_pyExport.cmake` file seems to have been added to the binary installation of ROS 2 since `humble` - it's not there  in `foxy` or `galactic` and my cross-compilation in these platforms works fine.

P.S. Apologies for not providing a reproducible example in this case. Let me know whether the above make sense and I cna then spend the time to come up with one afterwards.

**Comment by clalancette** [comment] 2023-06-15 17:07
This one looks like the cross-compilation environment isn't setup properly.  In particular, it is common for us to have hard-coded paths to the system libraries in our distributed debians.  But in a cross-compilation environment, it should not be using those libraries at all, and those libraries should be cross-compiled as well.

**Comment by clalancette** [comment] 2023-07-24 15:53
I'm going to close this one out, but feel free to reopen or keep commenting if you are still having issues.

**Closed by clalancette** 2023-07-24 15:53 UTC
Labels: more-information-needed

**Comment by Ryanf55** [comment] 2024-05-14 18:29
If I were to supply a minimum reproducible example on cross-compile environment for ROS 2, would it be more likely that this issue were prioritized?  

With [cross_compile](https://github.com/ros-tooling/cross_compile) archived and QEMU slow, using a CMake toolchain to do cross compile against a sysroot without QEMU is a really attractive approach.

**Comment by 3473f** [comment] 2024-06-12 08:54
I have a similar cross-compilation setup under Ubuntu 20.04 and ROS 2 Humble, which works with both CMake and Python packages, but not for interfaces packages. I run into the issue that the path of my target sysroot `/targetfs/usr/lib/aarch64-linux-gnu/libpython3.8.so` gets hardcoded. When I use the interfaces package on my actual target, it will still look for `libpython3.8.so` under `/targetfs/usr/lib/aarch64-linux-gnu/libpython3.8.so` and not `/usr/lib/aarch64-linux-gnu/libpython3.8.so`.

That's how my enviromenmt is setup

```shell
set(TARGET_ROOT_PATH /targetfs)

set(CMAKE_SYSROOT ${TARGET_ROOT_PATH})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

Looking at the logs, this seems to result in the correct pathes being found

```
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Found rosidl_adapter: 3.1.5 (/targetfs/opt/ros/humble/share/rosidl_adapter/cmake)
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found ament_cmake_ros: 0.10.0 (/targetfs/opt/ros/humble/share/ament_cmake_ros/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3.6") 
-- Found python_cmake_module: 0.10.0 (/targetfs/opt/ros/humble/share/python_cmake_module/cmake)
-- Found PythonLibs: /targetfs/usr/lib/aarch64-linux-gnu/libpython3.8.so (found suitable version "3.8.10", minimum required is "3.5") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using PYTHON_INCLUDE_DIRS: /targetfs/usr/include/python3.8
-- Using PYTHON_LIBRARIES: /targetfs/usr/lib/aarch64-linux-gnu/libpython3.8.so
-- Found PythonExtra: .so  
-- Configuring done
-- Generating done
```

**Comment by mtawata** [comment] 2024-08-20 04:26
A workaround to the "No rule to make target '/usr/lib/aarch64-linux-gnu/libpython3.10.so', needed by" problem that @nikoskoukis-slamcore posted above: 

If sysroot is located in `CMAKE_SYSROOT`, run (may need sudo):

```bash
mkdir -p /usr/lib/aarch64-linux-gnu
ln -s ${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/libpython3.10.so /usr/lib/aarch64-linux-gnu/libpython3.10.so
```

This will cause `make` to see that the target exists and succeed.  When running on target device, `ld` will still be able to find the `.so` file properly at `/usr/lib/aarch64-linux-gnu/libpython3.10.so`.  Hope that helps others who come across this issue!
